stages:
  - build
  - test
  - quality
  - package
  - deploy

variables:
  MAVEN_CLI_OPTS: >
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
    --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  PWD: ip172-18-0-51-bihm1906chi000b37l6g  # ← remplace par ton hostname Play-With-Docker réel
  DOCKER_HOST: tcp://$PWD:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH/myapp:latest

build_job:
  stage: build
  image: eclipse-temurin:17-jdk-alpine
  script:
    - ./mvnw compile $MAVEN_CLI_OPTS
  cache:
    paths:
      - .m2/repository

test_job:
  stage: test
  image: eclipse-temurin:17-jdk-alpine
  script:
    - ./mvnw test $MAVEN_CLI_OPTS
  cache:
    paths:
      - .m2/repository

code_quality_job:
  stage: quality
  image: codeclimate/codeclimate
  script:
    - codeclimate analyze -f html > gl-code-quality-report.html
  artifacts:
    paths:
      - gl-code-quality-report.html
  allow_failure: true

package_job:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-cli-compose
  script:
    - docker compose build
    - docker compose push  # facultatif si image envoyée vers registry
  only:
    - main

deploy_staging_job:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache docker-cli-compose
  script:
    - docker compose -H tcp://$PWD:2375 up -d
  environment:
    name: staging
    url: http://$PWD-8080.direct.labs.play-with-docker.com
  only:
    - main
